Product database
MelvinCou/cash-manager pull request #41
Opened 2023-12-04 13:36 UTC by MansourWolou

Creation of table and connexion to database

Linked #39

2023-12-05 13:06 UTC, MelvinCou commented on Server/shop/src/main/java/com/cashmanager/server/shop/Product.java
> +    private String productUrl;
Add `@Column( nullable = false)` for each field
non of theme are nullable

2023-12-05 13:16 UTC, MelvinCou requested changes

2023-12-05 13:16 UTC, MelvinCou commented on Server/shop/src/main/java/com/cashmanager/server/shop/Order.java
> +    private UUID order_id;
We already know that we are in an Order, this is not a foreign key

```suggestion
    private UUID id;
```

2023-12-05 13:16 UTC, MelvinCou commented on Server/shop/src/main/java/com/cashmanager/server/shop/Order.java
> +    private Set<Ordered_orders> ordered_orders;
```suggestion
    private Set<Ordered_orders> orderedOrders;
```

2023-12-05 13:16 UTC, MelvinCou commented on Server/shop/src/main/java/com/cashmanager/server/shop/Ordered_orders.java
> +public class Ordered_orders {
```suggestion
public class OrderedOrders {
```

2023-12-05 13:16 UTC, MelvinCou commented on Server/shop/src/main/java/com/cashmanager/server/shop/Ordered_orders.java
> +    private UUID ordered_orders_id;
```suggestion
    private UUID id;
```

2023-12-05 19:34 UTC, MelvinCou requested changes

2023-12-05 19:34 UTC, MelvinCou commented on Server/shop/src/main/java/com/cashmanager/server/shop/Order.java
> +    private UUID orderId;
Please stay simple, use only `table_id` naming for foreign keys.
Also do that for the other tables.

```suggestion
    private UUID id;
```

2023-12-05 19:46 UTC, MeloLawson requested changes

2023-12-05 19:46 UTC, MeloLawson commented on Server/shop/src/main/java/com/cashmanager/server/shop/Order.java
> +    @Column(name = "order_id" ,nullable = false)
for the primary key, maybe name it only "id" and not "order_id"

2023-12-05 19:46 UTC, MeloLawson commented on Server/shop/src/main/java/com/cashmanager/server/shop/Order.java
> +
be careful on the field naming, "orderedOrders" and not "ordered_orders"
```suggestion
private Set<OrderedOrder> orderedOrders;
```

2023-12-05 19:46 UTC, MeloLawson commented on Server/shop/src/main/java/com/cashmanager/server/shop/OrderedOrder.java
> +    private UUID orderedOrdersId;
same remark for the primary key name
```suggestion
    private UUID id;
```

2023-12-05 19:46 UTC, MeloLawson commented on Server/shop/src/main/java/com/cashmanager/server/shop/OrderedOrder.java
> +    private Product products;
There is only one product, so the field should not be plural
```suggestion
    private Product product;
```

2023-12-05 19:46 UTC, MeloLawson commented on Server/shop/src/main/java/com/cashmanager/server/shop/OrderedOrder.java
> +    private Order orders;
There is only one order, so the field should not be plural
```suggestion
    private Order order;
```

2023-12-05 19:46 UTC, MeloLawson commented on Server/shop/src/main/java/com/cashmanager/server/shop/Product.java
> +    private UUID productId;
```suggestion
    private UUID id;
```

2023-12-05 19:46 UTC, MeloLawson commented on Server/shop/src/main/java/com/cashmanager/server/shop/Product.java
> +    private Set<OrderedOrder> ordered_orders;
```suggestion
    private Set<OrderedOrder> orderedOrders;
```

2023-12-08 18:54 UTC, MelvinCou commented on Server/shop/src/main/java/com/cashmanager/server/shop/OrderedOrder.java
> +    private UUID orderedOrderId;
```suggestion
    private UUID Id;
```

2023-12-11 07:51 UTC, MelvinCou approved these changes

2023-12-11 16:00 UTC, MeloLawson approved these changes

2023-12-18 09:52 UTC, MelvinCou approved these changes

2023-12-18 10:04 UTC, merged