Database for bank
MelvinCou/cash-manager pull request #43
Opened 2023-12-06 20:28 UTC by MelvinCou

- JPA for bank
- Simple unit test of a user
`mvn --projects :database test`
- devcontainer
- `account`, `transaction` and `database` modules
- `compose.yaml` at repo's root for Inteliji + env exemples

~:warning: Accidentally deleted `Server/product/compose.yaml `, do not merge for now.~ It has been corrected.

Closes #37

2023-12-08 20:02 UTC, MeloLawson requested changes
About the organization in the database module, usually in java, repositories and entities are in different packages

2023-12-11 13:48 UTC, MelvinCou commented on Server/bank/database/src/main/java/com/cashmanager/server/database/repositories/account/AccountsLogs.java
> +public class AccountsLogs {
It seems to be hard to implement :
- logback starts before spring, but requires database available when started. So postgres must run separately.
- logback also logs spring logs, which is very verbose.
- Add custom fields in database is complicated.

2023-12-12 14:40 UTC, MeloLawson requested changes

2023-12-12 14:40 UTC, MeloLawson commented on Server/bank/database/src/main/java/com/cashmanager/server/database/entities/Account.java
> +    private UUID id;
You can choose a auto-generate strategy for the primary key in the database
```suggestion
@GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
```

2023-12-12 14:40 UTC, MeloLawson commented on Server/bank/database/src/main/java/com/cashmanager/server/database/entities/AccountsLogs.java
> +    private UUID id;
same remark for the auto-generation of the primary key

2023-12-12 16:08 UTC, MansourWolou approved these changes
didn't read all but ok :+1:

2023-12-12 16:13 UTC, MeloLawson approved these changes
ok !

2023-12-12 16:13 UTC, merged